### ISSUE TITLE
Data_root for watermarking stable diffusion

### ISSUE THREAD

**Issue by turned2670** [yunqing-me/WatermarkDM#1]
Thank you for this excellent work. I am trying to watermark stable diffusion using the following command:
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --base configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml \
                 --train --gpus 0,1,2,3 \
                 --actual_resume ../_model_pool/sd-v1-4-full-ema.ckpt  \
                 --data_root ../_target_samples/watermark/*/*.png \
                 --w_reg_weight 1e-7 \
                 --name watermark_toy_V_ft_w_reg_l1_1.0e-7 \
But I'm wondering that "data_root" should contain what kind of dataset/images? Looking foward to your reply.

**Comment by njuaplusplus** [comment]
I have the same question here. Wonder if anyone can provide any idea on how to run the code.

**Comment by yunqing-me** [comment]
Thank you for your interest in our work. Let me reply to you soon.

**Comment by yunqing-me** [comment]
Thank you all for the interest in our work. 

The `data_root` should be the user-defined target image (e.g., could be any image you want) that you aim to embed in the text-to-image model. For example, it could be a photo of a toy. 

This image is corresponding to the **Predefined watermark image** in Figure 2 (Bottom) in our paper. In that case, it is a qr-code image.

**Comment by xbtzpx** [comment]
> 我在这里有同样的问题。想知道是否有人可以提供有关如何运行代码的任何想法。

有会运行代码的同学么，我也需要帮助，真的非常感谢。我的邮箱1191496157@qq.com
