### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by chbw818** [yunqing-me/WatermarkDM#10]
Sorry to bother you again.I met a strange error when I run the main.py using the following command:
`CUDA_VISIBLE_DEVICES=0 python main.py --base configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml \
                 --train --gpus 0, \
                 --actual_resume ../_model_pool/sd-v1-4-full-ema.ckpt  \
                 --data_root ../_target_samples/watermark/*/*.png \
                 --w_reg_weight 1e-7 \
                 --name watermark_toy_V_ft_w_reg_l1_1.0e-7 \`
`NotADirectoryError:` [Errno 20] Not a directory: '../_target_samples/watermark/v/V.png'
Then I tried the following command:
`CUDA_VISIBLE_DEVICES=0 python main.py --base configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml \
                 --train --gpus 0,\
                 --actual_resume ../_model_pool/sd-v1-4-full-ema.ckpt  \
                 --data_root ../_target_samples/watermark/*/ \
                 --w_reg_weight 1e-7 \
                 --name watermark_toy_V_ft_w_reg_l1_1.0e-7 \`
`IsADirectoryError:` [Errno 21] Is a directory: '../_target_samples/watermark/V/.ipynb_checkpoints'`
I wonder how to solve this problem.Looking forward to your reply!

**Comment by yunqing-me** [comment]
Hi, 
it seems that you are specifying a particular image in `--data_root`. To solve this, perhaps you can use **path to your images** in `--data_root`.

hope this can help you

**Comment by chbw818** [comment]
Sorry,this problem still troubles me.
I tried the command like this:
`CUDA_VISIBLE_DEVICES=0 python main.py --base configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml --train --gpus 0, --actual_resume ../_model_pool/sd-v1-4-full-ema.ckpt --data_root ../_target_samples/watermark/V/ --w_reg_weight 1e-7 --name watermark_toy_V_ft_w_reg_l1_1.0e-7`
but it didn't work. 
`Original Traceback (most recent call last):
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/WatermarkDM/sd_watermark/main.py", line 259, in __getitem__
    return tuple(d[idx] for d in self.datasets)
  File "/root/WatermarkDM/sd_watermark/main.py", line 259, in <genexpr>
    return tuple(d[idx] for d in self.datasets)
  File "/root/WatermarkDM/sd_watermark/ldm/data/personalized_watermark.py", line 188, in __getitem__
    image = Image.open(self.image_paths[i % self.num_images])
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/PIL/Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '../../autodl-tmp/targetsample/.ipynb_checkpoints'`
could you give me a more specific example？
thanks!

**Comment by chbw818** [comment]
The problem have been solved.Thanks!
I run the program on a Autodl server, there is a hidden file named. ipynb in the same path as V.jpg
After I deleted it, this problem was solved.
