### ISSUE TITLE
I got the error when I tried to run the sd-watermarking experiment 

### ISSUE THREAD

**Issue by HoJ-Onle** [yunqing-me/WatermarkDM#12]
I tried to run this command:
'CUDA_VISIBLE_DEVICES=1 python main.py --base ./configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml \
                --train --gpus 0 \
                --actual_resume ../checkpoints/sd-v1-4-full-ema.ckpt  \
                --data_root ../watermarking/ \
                --w_reg_weight 1e-7 \
                --name temp \
                --wandb_project_name temp-proj \
                --wandb_run_name temp-run \'

And I met a mistake as follows:
AttributeError: 'CLIPTextEmbeddings' object has no attribute 'embedding_forward'

**Comment by yunqing-me** [comment]
Could you please try to run on at least 2 gpus and see if there is any difference?
