### ISSUE TITLE
how to solve this 

### ISSUE THREAD

**Issue by jinganglang567** [yunqing-me/WatermarkDM#15]
def extract_fingerprints():
    all_fingerprinted_images = []
    all_fingerprints = []
    bitwise_accuracy = 0

    BATCH_SIZE = args.batch_size
    
    # transform gt_fingerprints to 
    gt_fingerprints  = "0100"
    fingerprint_size = len(gt_fingerprints)
    '''z = torch.zeros((args.batch_size, fingerprint_size), dtype=torch.float)
    for (i, fp) in enumerate(gt_fingerprints):
        z[:, i] = int(fp)
    z = z.cuda()'''
    # xiu
    fingerprint_batch = torch.tensor([[int(c) for c in gt_fingerprints]] * BATCH_SIZE, dtype=torch.float32)
    z = fingerprint_batch.cuda()
    # xiu

    dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
    #dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    for images, _ in tqdm(dataloader):
        images = images.to(device)
        #xiu
        batch_size = images.shape[0]
        if batch_size != BATCH_SIZE:
            fingerprint_batch = torch.tensor([[int(c) for c in gt_fingerprints]] * batch_size, dtype=torch.float32)
            z = fingerprint_batch.cuda()
        #xiu
        fingerprints = RevealNet(images)
        fingerprints = (fingerprints > 0).long()

        #bitwise_accuracy += (fingerprints[: images.size(0)].detach() == z[: images.size(0)]).float().mean(dim=1).sum().item()
        #xiu
        bitwise_accuracy += (fingerprints.detach() == z[: batch_size]).float().mean(dim=1).sum().item()

        all_fingerprinted_images.append(images.detach().cpu())
        all_fingerprints.append(fingerprints.detach().cpu())

    dirname = args.output_dir
    # if not os.path.exists(dirname):
    #     os.makedirs(dirname)
    
    all_fingerprints = torch.cat(all_fingerprints, dim=0).cpu()
    bitwise_accuracy = bitwise_accuracy / len(all_fingerprints)
    print(f"Bitwise accuracy on fingerprinted images: {bitwise_accuracy}") # non-corrected

error
Traceback (most recent call last):
  File "detect_watermark_cifar10.py", line 195, in <module>
    main()
  File "detect_watermark_cifar10.py", line 191, in main
    extract_fingerprints()
  File "detect_watermark_cifar10.py", line 136, in extract_fingerprints
    bitwise_accuracy += (fingerprints.detach() == z[: batch_size]).float().mean(dim=1).sum().item()
RuntimeError: The size of tensor a (64) must match the size of tensor b (4) at non-singleton dimension 1

**Comment by jinganglang567** [comment]
sorry to bother you I think the problem is the decoder return a (64,64) tensor ,but thr correct size should be (64,4) so if the model is the problem?

**Comment by yunqing-me** [comment]
Thank you for the interest in the work. 

A first impression: there are some dimension issues in your code, and it should be mentioned that the resolution for cifar is 32x32, otherwise it is 64x64 for all other datasets.

I will take a look at your case. Before that, you can provide the arguments used in your code. e.g., dataset, hyperparameter, etc.

**Comment by jinganglang567** [comment]
ok i think where is the problem when i train the encoder and decoder the bit length is 64 but the detect is 0100 is 4
