### ISSUE TITLE
Can i train the sd-watermark for only one gpu?

### ISSUE THREAD

**Issue by zhaojunGUO** [yunqing-me/WatermarkDM#19]

**Comment by yunqing-me** [comment]
Hi: Thanks for the interest. We followed the public implementation and please see their configurations: 
[XavierXiao/Dreambooth-Stable-Diffusion](https://github.com/XavierXiao/Dreambooth-Stable-Diffusion#:~:text=I%20train%20the%20model%20use%20two%20A6000%20GPUs%20and%20it%20takes%20~15%20mins.). It is recommended to use at least 2 gpus with at least 24GB memory.
