### ISSUE TITLE
Gaussian noise attacks

### ISSUE THREAD

**Issue by Jayamoon59** [yunqing-me/WatermarkDM#3]
Hello, I want to run a robustness test, but I don't know how to add Gaussian noise attacks to the model weights? In which file should the code be added? What code statement to add?

**Comment by yunqing-me** [comment]
Hi, Thank you for your interest in our work.

Let me reply to you soon in this week.

**Comment by yunqing-me** [comment]
To add Gaussian noise attack to the model weights, you may need to refer to the image generation script.
- see `./edm/generate.py`
You can directly add noise to the weights via:
```
    # ---- add noise to model weights ---- #
    with torch.no_grad():
        for param in net.parameters():
            noise = torch.randn_like(param) * 15e-3  # we use 15e-3 as noise strength in this example
            param += noise
    # ---------------------------- #
```
and then generate images as usual.
