### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'noise_2.pt'

### ISSUE THREAD

**Issue by MrDongdongLin** [yunqing-me/WatermarkDM#4]
Hi Zhao,

I am interested in this work for DM watermarking, and this project does provide a good benchmark for implementation. Thank you for your great work! However, I am curious about SD model watermarking in this project. I got an error when I load the model noise_{self.num_vis_samples}.pt, as follows:

https://github.com/yunqing-me/WatermarkDM/blob/a12ed89c84256a2520468052b7ab5165607041a7/sd_watermark/ldm/models/diffusion/ddpm.py#L473

Do you have the pretrained weight of this model or could you tell me how to train this noise model?

Best regards,
Donny

**Comment by yunqing-me** [comment]
Thank you for your interest in our work.

Let me check a bit and reply to you soon.

Thanks,
Yunqing

**Comment by njuaplusplus** [comment]
The noise_2.pt is a tensor of random noise.
You can use `python noise_generation.py` to generate it.

https://github.com/yunqing-me/WatermarkDM/blob/main/sd_watermark/noise_generation.py

**Comment by MrDongdongLin** [comment]
> The noise_2.pt is a tensor of random noise. You can use `python noise_generation.py` to generate it.
> 
> https://github.com/yunqing-me/WatermarkDM/blob/main/sd_watermark/noise_generation.py

Got it, thank you very much!
