### ISSUE TITLE
error&dataset

### ISSUE THREAD

**Issue by xbtzpx** [yunqing-me/WatermarkDM#6]
hello,I met some mistakes, you know how to solve?
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined.

And I have some questions about the data set, what is the data set used when running the sd_watermark.py code?

**Comment by MrDongdongLin** [comment]
Remove 'CUDA_VISIBLE_DEVICES=xxx' since 'gpus' has been defined in the command.

**Comment by MrDongdongLin** [comment]
> hello,I met some mistakes, you know how to solve? if trainer.global_rank == 0: NameError: name 'trainer' is not defined.
> 
> And I have some questions about the data set, what is the data set used when running the sd_watermark.py code?


Remove 'CUDA_VISIBLE_DEVICES=xxx' since 'gpus' has been defined in the command.

**Comment by xbtzpx** [comment]
> > 你好，我遇到了一些错误，你知道怎么解决吗？如果trainer.global_rank == 0：名称错误：未定义名称“训练师”。
> > 我对数据集有一些疑问，运行sd_watermark.py代码时使用的数据集是什么？
> 
> 删除“CUDA_VISIBLE_DEVICES=xxx”，因为命令中已定义“gpus”。


But when I run main.py, the "os.environ["CUDA_VISIBLE_DEVICES"]="0""  is commented out

**Comment by MrDongdongLin** [comment]
> > > 你好，我遇到了一些错误，你知道怎么解决吗？如果trainer.global_rank == 0：名称错误：未定义名称“训练师”。
> > > 我对数据集有一些疑问，运行sd_watermark.py代码时使用的数据集是什么？
> > 
> > 
> > 删除“CUDA_VISIBLE_DEVICES=xxx”，因为命令中已定义“gpus”。
> 
> But when I run main.py, the "os.environ["CUDA_VISIBLE_DEVICES"]="0"" is commented out

Try to use the command like (Remove the CUDA_VISIBLE_DEVICES and modify param --gpus):
python main.py --base configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml \
                 --train --gpus 0,1,2,3 \
                 --actual_resume ../_model_pool/sd-v1-4-full-ema.ckpt  \
                 --data_root ../_target_samples/watermark/*/*.png \
                 --w_reg_weight 1e-7 \
                 --name watermark_toy_V_ft_w_reg_l1_1.0e-7 \`

**Comment by njuaplusplus** [comment]
What is the full traceback for the error?

**Comment by yunqing-me** [comment]
Thank you for the interest in our work. I see that the issues are cluttered.

Should there be any further issues, please consider re-creating an issue.

**Comment by jinganglang567** [comment]
hi,sorry to bother you i got th same problem,how did you solve it
