### ISSUE TITLE
about https://github.com/yunqing-me/WatermarkDM#watermarking-stable-diffusion

### ISSUE THREAD

**Issue by Jayamoon59** [yunqing-me/WatermarkDM#7]
Hello, I am very glad to hear your reply to my question last time. There was a problem when I was replicating stable-diffusion, which confused me.

When I run sd_watermark/main.py, it only takes a minute or two to run and show finish with code 0.

And there are some bar graphs on the wandb visualization site, I don't know if this.py file is a training file? If so, which of my actions went wrong?

Looking forward to your reply.

**Comment by yunqing-me** [comment]
> When I run sd_watermark/main.py, it only takes a minute or two to run and show finish with code 0.

It seems that your number of training steps is too low, and the script ends fastly. You can tune the number of training steps (iterations) [here](https://github.com/yunqing-me/WatermarkDM/blob/a12ed89c84256a2520468052b7ab5165607041a7/sd_watermark/configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml#L10C5-L10C20).

> And there are some bar graphs on the wandb visualization site, I don't know if this.py file is a training file?

The script will log the training steps. And yes, `main.py` is the training file. Specifically, you can refer to this bash script (as in README) for tranining, and you can tune the hyperparameters.
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --base configs/stable-diffusion/v1-finetune_unfrozen_watermark.yaml \
                 --train --gpus 0,1,2,3 \
                 --actual_resume ../_model_pool/sd-v1-4-full-ema.ckpt  \
                 --data_root ../_target_samples/watermark/*/*.png \
                 --w_reg_weight 1e-7 \
                 --name watermark_toy_V_ft_w_reg_l1_1.0e-7 \
```
