### ISSUE TITLE
CUDA error: invalid device ordinal in train.py

### ISSUE THREAD

**Issue by Krish2002** [yunqing-me/WatermarkDM#8]
torchrun --standalone --nproc_per_node=8 train.py 
    --outdir=training-runs \
    --data=datasets/cifar10-32x32.zip 
    --cond=1 
    --arch=ddpmpp
    
    while running this script it gives me CUDA error: invalid device ordinal. 
    I have checked the compatibality of versions too.

**Comment by yunqing-me** [comment]
`--nproc_per_node=8` denotes there are 8 available gpus on our machine.

You can change the command based on your hardware environment.
