### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '*.pkl'

### ISSUE THREAD

**Issue by chbw818** [yunqing-me/WatermarkDM#9]
Thank you for this excellent work.I got an error when I trying to compute the FID using the following command.
```
torchrun --standalone --nproc_per_node=1 generate.py --outdir=cifar10_tmp --seeds=0-49999 --subdirs \
    --network=*.pkl
```
I have placed the. pkl file generated by training and generate.py file in the same path, which seems to recognize *.pkl as specific file names. How can I solve this problem?

**Comment by yunqing-me** [comment]
Thank you for your interest in our work. 

Please rename `*.pkl` using the name/dir of your `.pkl` file.

**Comment by chbw818** [comment]
Thank you for your reply.I misunderstood.
